Repository so-mouga/memoriz-back, pull requests merged in 2019-03, with the labels that each got.

#5 chore(infrastructure): add MakeFile commands and fix the command init-hooks
  Makefile
Labels: enhancement

#9 Feature/add code formatter
  .githooks/pre-commit
  .prettierignore
  .prettierrc.json
  Makefile
  package.json
Labels: Fixes to do, enhancement, question

#8 feat(back): Add token for connection user
  Makefile
  app.js
  controller/auth/auth.controller.js
  controller/user/user.controller.js
  firebase/auth.js
  firebase/configFirebase.json
  package-lock.json
  package.json
  utils/keys/jwtRS256.key
  utils/keys/jwtRS256.key.pub
  utils/token/token.js
  views/users/login.twig
Labels: Fixes to do
